modLoader = "javafml"
loaderVersion = "[32,)"
license = "GNU General Public License version 3 (GPLv3)"

[[mods]]
modId = "sneaky_tree_growing"
version = "1.7.1"
displayName = "Sneaky Tree Growing"
credits = "A Qubik Studios Project"
displayURL = "https://qubik-studios.net"
logoFile = "logo.png"
authors = "ConmineLP"
description = '''
Sneak to grow Trees!
'''

[[dependencies.sneaky_tree_growing]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sneaky_tree_growing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"


