modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId = "sneaky_tree_growing"
version = "1.7.0"
displayName = "Sneaky Tree Growing"
credits = "A Qubik Studios Project"
displayURL = "https://qubik-studios.net"
logoFile = "logo.png"
authors = "ConmineLP"
description = '''
Sneak to grow Trees!
'''

[[dependencies.sneaky_tree_growing]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sneaky_tree_growing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"


