modLoader = "javafml"
loaderVersion = "[38,)"
license = "GNU Lesser General Public License version 3 (LGPLv3)"
issueTrackerURL="https://github.com/Qubik-Studios/Sneaky-Tree-Growing/issues"

[[mods]]
modId = "sneaky_tree_growing"
version = "1.18.x-1.10.0"
displayName = "Sneaky Tree Growing"
credits = "ConmineLP, Maxthier, Kleidukos, Snail (Fabric Fix)"
displayURL = "https://qubik-studios.net"
logoFile = "logo.png"
authors = "Qubik Studios"
description = "Sneak to grow Trees!"


[[dependencies.sneaky_tree_growing]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sneaky_tree_growing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"


