modLoader = "javafml"
loaderVersion = "[41,)"
license = "GNU Lesser General Public License version 3 (LGPLv3)"
issueTrackerURL="https://github.com/Qubik-Studios/Sneaky-Tree-Growing/issues"

[[mods]]
modId = "sneaky_tree_growing"
version = "1.10.0-DEV.MultiversionUpdate119.1"
displayName = "Sneaky Tree Growing"
credits = "ConmineLP#8812, Maxthier#8158, Kleidukos#6654, Snail#5831 (Fabric Fix)"
displayURL = "https://qubik-studios.net"
logoFile = "logo.png"
authors = "Qubik Studios"
description = "Sneak to grow Trees!"


[[dependencies.sneaky_tree_growing]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sneaky_tree_growing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"


