name: SneakyTreeGrowing
version: '${version}'
main: net.qubikstudios.sneakytreegrowing.SneakyTreeGrowing
api-version: 1.19
authors: [ Kleidukos ]
commands:
  SneakyTreeGrowing:
    usage: /stg toggle <tree/crops/tags> (need op permission)
    description: Use toggle <tree/crops/tags> for toggle the growing modes
    aliases:
      - sneakygrowing
      - stg
permissions:
  stg.toggle:
    description: Allows you to use /stg toggle
    default: op